---
- name: Restart Nginx on remote host
  hosts: localhost
  become: true
  tasks:
    - name: Restart Nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
